name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 11 for building the project
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'

      # Set up JDK 17 for Gradle (if required for newer versions)
      - name: Set up JDK 17 for Gradle
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      # Cache Gradle dependencies to speed up subsequent builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set execute permissions for gradlew script
      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      # Build Release AAB
      - name: Build Release AAB
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64
        run: ./gradlew bundleRelease

      # List contents of the release directory for debug purposes
      - name: List contents of the release directory
        run: |
          echo "Checking the release directory"
          ls -l ./app/build/outputs/bundle/release/

      # Check if the AAB exists before proceeding
      - name: Check if AAB exists
        run: |
          if [ -f ./app/build/outputs/bundle/release/app-release.aab ]; then
            echo "AAB file exists!"
          else
            echo "AAB file does not exist!" && exit 1
          fi


#      - name: Debug GitHub Secrets
#        run: |
#          echo "Google Play Service Account Loaded: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
      - name: Debug Google Play Service Account
        run: |
          if [ -z "${{ secrets.GOOGLE_PLAY_JSON_KEY }}" ]; then
            echo "Service account not loaded!"
          else
            echo "Service account loaded"
          fi
      # Deploy to Google Play (Internal Test)
      - name: Deploy to Google Play (Internal Test)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}
          packageName: com.cicdtest
          releaseFiles: ./app/build/outputs/bundle/release/app-release.aab
          track: internal
          inAppUpdatePriority: 0
          status: completed
          changesNotSentForReview: false
