name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 11 for building the project
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'

      # Set up JDK 17 for Gradle (if required for newer versions)
      - name: Set up JDK 17 for Gradle
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      # Cache Gradle dependencies to speed up subsequent builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set execute permissions for gradlew script
      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      # Build Release AAB
      - name: Build Release AAB
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64
        run: ./gradlew bundleRelease

      # Print current working directory
      - name: Print Current Working Directory
        run: pwd

      # List files in the release folder
      - name: List files in release folder
        run: ls -R ./app/build/outputs/bundle/release/

      # Step 5: List files in the build output directory (for debugging)
      - name: List files in build directory
        run: ls -R ./app/build/outputs/

      - name: Check file permissions
        run: ls -l ./app/build/outputs/bundle/release/

      # Check file existence and permissions
      - name: Check if AAB file exists
        run: |
          if [ -f ./app/build/outputs/bundle/release/app-release.aab ]; then
            echo "AAB file exists at: $(pwd)/app/build/outputs/bundle/release/app-release.aab"
          else
            echo "AAB file does not exist!" && exit 1
          fi

      # Deploy to Google Play (Internal Test) without printing sensitive data
      - name: Deploy to Google Play (Internal Test)
        uses: r0adkll/upload-google-play@v1
#        uses: r0adkll/upload-google-play@v1.0.15
        with:
#          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}  # Do not expose secrets directly in logs
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}  # Do not expose secrets directly in logs
          packageName: com.cicdtest
          releaseFiles: ${{ github.workspace }}/app/build/outputs/bundle/release/app-release.aab  # Use absolute path if necessary
          track: internal
          userFraction: 1
          inAppUpdatePriority: 5
          status: completed
          changesNotSentForReview: false
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64

