#name: Build
#
#on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: 11
#          distribution: 'temurin'
#
#      - name: Set up JDK 17 for Gradle
#        uses: actions/setup-java@v2
#        with:
#          java-version: 17
#          distribution: 'temurin'
#
#      - name: Cache Gradle dependencies
#        uses: actions/cache@v4
#        with:
#          path: ~/.gradle/caches
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      - name: Set execute permissions for gradlew
#        run: chmod +x ./gradlew
#
#      - name: Build Release APK
#        env:
#          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.14-7/x64
#        run: ./gradlew assembleRelease
#
#      - name: Upload APK artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: Release-apk
#          path: app/build/outputs/apk/release/app-release.apk